cfq-iosched: Adjust one function call together with a variable assign… …ment
The script "checkpatch.pl" pointed information out like the following.

ERROR: do not use assignment in if condition

Thus fix the affected source code place.

Signed-off-by: Markus Elfring <elfring@users.sourceforge.net>
Signed-off-by: Jens Axboe <axboe@fb.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>